module.exports = {
    AUTO_VIEW_STATUS: 'true',
    AUTO_LIKE_STATUS: 'true',
    AUTO_RECORDING: 'true',
    AUTO_LIKE_EMOJI: ['🌸', '🪴', '💫', '🍂', '🌟','🫀', '👀', '🤖', '🚩', '🥰', '🗿', '💜', '💙', '🌝', '🖤', '💚'],
    PREFIX: '.',
    MAX_RETRIES: 3,
    GROUP_INVITE_LINK: 'https://chat.whatsapp.com/Hdyl83NUMUL64M6TfCkd84?mode=gi_t,
    ADMIN_LIST_PATH: './admin.json',
    IMAGE_PATH: 'https://files.catbox.moe/vmnp79.png',
    NEWSLETTER_JID: '120363408050684565@newsletter',
    NEWSLETTER_MESSAGE_ID: '428',
    OTP_EXPIRY: 300000,
    NEWS_JSON_URL: '',
    BOT_NAME: '𝐍𝐀𝐈𝐋 𝐂ʏʙᴇʀ 𝐁𝐎𝐓',
    OWNER_NAME: 'ᴍʀ ɴᴀɪʟ',
    OWNER_NUMBER: '93781615620',
    BOT_VERSION: '1.0.2',
    BOT_FOOTER: '>  ᴘᴏᴡᴇʀᴇᴅ ʙʏ ɴᴀɪʟ ᴄʏʙᴇʀ ',
    CHANNEL_LINK: 'https://whatsapp.com/channel/0029VbC6cDY96H4T7qEN8K1m',
};
